### ISSUE TITLE
Increase timeout on bluetoothSerial.list()?

### ISSUE THREAD

**Issue by mrtomhoward** [don/BluetoothSerial#101]
For the BLE device I'm working with, the engineer wants to reduce the advertising rate to 5 seconds to minimise power consumption.

It seems this is too slow for the bluetoothSerial.list() method.

Is this configurable somewhere?

**Comment by don** [comment]
@mrtomhoward the scan time is not configurable yet.

You'll need to edit this in 2 places: the call to [scan](https://github.com/don/BluetoothSerial/blob/fdca9cf6d3bc0bfeebadec62c335934952b8440f/src/ios/MEGBluetoothSerial.m#L155) and the [timer](https://github.com/don/BluetoothSerial/blob/fdca9cf6d3bc0bfeebadec62c335934952b8440f/src/ios/MEGBluetoothSerial.m#L157).

I need to think about the API change. Scan time could passed as additional parameter to `list` or perhaps a plugin configuration that can be adjusted.

**Comment by mrtomhoward** [comment]
@don That works nicely, many thanks for the quick reply.

**Comment by sclearion** [comment]
Thanks
