### ISSUE TITLE
Error connecting to bluetooth devices

### ISSUE THREAD

**Issue by tridentNestea** [don/BluetoothSerial#103]
I'm having issues connecting to bluetooth devices through this plugin with my android phone. When I try to connect to my Mac Mini I can see that a connection has been established through the bluetooth icon on the system tray. But after 15-20 seconds I get an error on the app saying that the connection was lost and on the mac the connection in the systems tray is also lost. I'm using the chat sample app btw.

**Comment by don** [comment]
I don't think this will work. The Android code expects the other device to provide Serial Port Profile (SPP) and have the RFCOMM UUID 00001101-0000-1000-8000-00805F9B34FB. I don't think your Mac Mini provides SPP support.

**Comment by tridentNestea** [comment]
Okay thanks for the quick reply, I'll have to try find a different device for testing.
