### ISSUE TITLE
Cannot connect nexus 4 to nexus 5 

### ISSUE THREAD

**Issue by tanzeelrana** [don/BluetoothSerial#105]
Hey guys, 

were you able to connect 2 android devices successfully using this plugin ? 

I followed all the steps, built the app and installed it on my phones. when I try to connect from my nexus 4 to my nexus 5 or vice versa. I get a message connecting ... , later on I see a message "Disconnected"

Can someone help me on this please ?

**Comment by don** [comment]
See #50 for more info. Closing this one as a duplicate.
