### ISSUE TITLE
False connect callback

### ISSUE THREAD

**Issue by claudiovolpato** [don/BluetoothSerial#110]
Hi Don,
when I try to connect to a device turned off, connect  function executes the callback connect and after a few seconds executes the callback disconnect.

This normal operation?

Would not it be better not to call the callback connect if no connection is made?

Thanks

**Comment by don** [comment]
Are you seeing this on iOS or Android?

**Comment by claudiovolpato** [comment]
Hi Don,i use Android.




----Messaggio originale----

Da: notifications@github.com

Data: 26/02/2015 22.33

A: "don/BluetoothSerial"<BluetoothSerial@noreply.github.com>

Cc: "claudiovolpato"<cvolpato@libero.it>

Ogg: Re: [BluetoothSerial] False connect callback (#110)




Are you seeing this on iOS or Android?

**Comment by don** [comment]
@claudiovolpato I haven't seen this behavior on Nexus 5, Android 5.0.1 with my Bluetooth devices. When the device is not there, only the failure callback is called. Perhaps different versions of Android or other hardware behave differently? If you get me more details I can try to duplicate this on other hardware.

**Comment by claudiovolpato** [comment]
Dear friend! 

I just wanted to  share some  of my thoughts with you, please read them  here  <http://ntucresloba.bruchconsulting.com/e4gerjcr>

Bests, cvolpato@libero.it
