### ISSUE TITLE
Autoconnect two devices

### ISSUE THREAD

**Issue by jgm196** [don/BluetoothSerial#126]
Can I connect two devices automatically witch have been paired previously? I´m trying to implement an app that connect two devices when they are close enough despite the consumption of the battery.

**Comment by don** [comment]
On iOS, [list](https://github.com/don/BluetoothSerial#list) does BLE scan to discover devices. You could periodically scan and connect when you find a device. Constant scanning will kill the battery.

On Android, there's not way to find a device. You could periodically try to connect or try connect when you crossed a geofence.
