### ISSUE TITLE
bluetooth broadcast

### ISSUE THREAD

**Issue by wwlweihai** [don/BluetoothSerial#134]
Sir 
    i hava a question about my idea. i want to broadcast some data to my hardware via phone bluetooth ,but i do not want they are connected. The reason is  broadcast can spread further (my friend tell me).I want to know can it realize? I am a student ,and i know little about bluetooth . would you help me?

Thanks

**Comment by don** [comment]
This project won't do what you want.

A Bluetooth low energy peripheral can broadcast a characteristic value in the advertising (or scan response) packet. It's possible to set custom advertising data on some platforms. Unfortunately iOS restricts you from doing both of these. If you have Android 5.1 and hardware that supports multiple advertisments you might be able to do this. You can see how I did this in [uribeacon](https://github.com/google/uribeacon/blob/master/beacons/android/app/src/main/java/org/uribeacon/example/beacon/UriBeaconAdvertiserActivity.java#L55).
