### ISSUE TITLE
PhoneGap Build issue

### ISSUE THREAD

**Issue by ccchai** [don/BluetoothSerial#145]
I am creating my app using PhoneGap Build BluetoothSerial plugin. It is working perfectly until I add another PhoneGap Build plugin, and my app fails to build for Android platform with the following error:

Error - Two of the plugins in your app are incompatible as they both add a file with the same name.

I suspect the problem is caused by this file:

[source-file src="src/android/org/apache/cordova/api/Dummy.java" target-dir="src/org/apache/cordova/api"/]

is it possible to offer a PhoneGap Build plugin without this Dummy.java or use more specific name like 'don_bluetoothSerial_dummy.java'?

**Comment by don** [comment]
Next version drops support for Cordova 2.9 (removes Dummy.java)
