### ISSUE TITLE
Not able to list devices on iOS for TSL devices

### ISSUE THREAD

**Issue by sonukapoor** [don/BluetoothSerial#148]
Hi, 

I am trying to connect my iPad to my bluetooth device from TSL. It works fine on Android, but on iOS it just doesn't return a list of devices. Here is the device I am using: http://www.tsl.uk.com/products/1128-bluetooth-handheld-uhf-rfid-reader/.

Thank you

**Comment by don** [comment]
[Your device](http://www.tsl.uk.com/products/1128-bluetooth-handheld-uhf-rfid-reader/) is Bluetooth Classic so it's not going to work with this plugin and iOS. 

![screen shot 2015-07-02 at 5 55 54 pm](https://cloud.githubusercontent.com/assets/3133/8488828/dcd5d5e6-20e3-11e5-990b-1d9dce56bad3.png)

When you're running on iOS, this plugin connects to a Bluetooth Low Energy device that has a service that looks like Bluetooth Classic SPP.

The device manufacturer might provide a SDK you can use to access the scanner on iOS using Bluetooth Classic. Maybe that's what they mean by "Apple iApp"? Generally you need to be part of the [MFi program](https://developer.apple.com/programs/mfi/) to use Bluetooth Classic on iOS.

It looks like your device can be configured as a Bluetooth Keyboard (Bluetooth HID). You might be able to use that to iOS to insert characters into the UI when you scan.

**Comment by sonukapoor** [comment]
Ok. But I am also not able to see any other devices. I should be able to see the bluetooth of my Samsung Note 4, right?

**Comment by sonukapoor** [comment]
@don I got it working with this one, which is a fork of your code:

https://github.com/matejkriz/BluetoothSerial/

**Comment by don** [comment]
@sonukapoor I'm glad you got it working. Are you submitting your app to the AppStore? Please let me know if you get the app approved using this fork.

**Comment by sonukapoor** [comment]
I will, but I am still testing it and I can see that the read is not working for me and readUntil, write and some other methods have not been implemented yet. Any chance you can help me out? It will be very appreciated.

**Comment by don** [comment]
@sonukapoor I don't have time to work on this now or the hardware for testing. Feel free to post stuff here but expect slow response since I'll be on the road for the next month or so.

**Comment by simoor** [comment]
@sonukapoor tried to get it working with Amp'ed too. I changed the RBL IDs in BLEDefines.h to the ones i found out via LightBlue (see https://github.com/don/BluetoothSerial/issues/141)

Was not able to get a list when using the list function. I tried both the version of @don and also the one of @matejkriz

Do you have any help for me, how did you get it working?

Thanks

**Comment by sclearion** [comment]
Same here. Using vanilla examples with an iPod 5 and a Samsung Galaxy note 5. Works GREAT Android but on ios the list() command returns nothing and does not allow you to specify the time limit. 3 seconds is nowhere near enough. Not seeing any of the 9 various bluetooth devices that the android command sees. The ios native bluetooth menu section sees everything like the droid, but the cordova application does not.

**Comment by don** [comment]
@sclearion iOS filters the Bluetooth LE scan results to only show supported low energy devices. You'll see more and different devices if you scan from the iOS Bluetooth settings. This plugin does not support Bluetooth Classic on iOS.

**Comment by sclearion** [comment]
So basically this "plugin does not work on with iOS" is what my boss is getting at and I think hes right. Even our BtLE devices are not showing up and we've tried on 3 different iphones and 2 ipod 5's. Seems like other people are having the same issue to. Had another dev shop try it across town and the same thing. Android works great but iOS is lacking. Nonetheless thank you for the work. We will use the Android portion and seek out a more rigorous BT soultion for our iOS

**Comment by don** [comment]
@sclearion The plugin most definitely works on iOS. Lots of people are using it. IT ONLY SUPPORTS SOME HARDWARE ON iOS. See [README](https://github.com/don/BluetoothSerial#supported-platforms). iOS works with RedBearLab BLE hardware, Adafruit Bluefruit LE, Laird BL600, an BlueGiga. This plugin does *not* support Bluetooth Classic on iOS.

If you need generic Bluetooth Low Energy support try [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central).

**Comment by sclearion** [comment]
"The plugin most definitely works on iOS" + "IT ONLY SUPPORTS SOME HARDWARE": does not make sense especially when NONE of the 12 BTLE devices we have here are showing up. Have a nice day

**Comment by simoor** [comment]
@sclearion you need to define the correct IDs or it cannot work by design of Bluetooth LE. If you configure the plugin and/or your device correctly, it will work fine. It wont list any devices if the correct IDs are missing. Had this issue too, and it was my fault. Please remember too that this plugin is used for Serial over BT
To find the IDs the LightBlue App on iOS might help you. Or you may ask your chip vendor.
