### ISSUE TITLE
ERR! parsing json 

### ISSUE THREAD

**Issue by georgedemian** [don/BluetoothSerial#149]
i have this error when i install the plugin

![image](https://cloud.githubusercontent.com/assets/11052170/8547433/101498a2-247c-11e5-9ff3-3f8e55694d25.png)

can you help me?

**Comment by don** [comment]
What version of Cordova are you using? What version of Node.js?

**Comment by georgedemian** [comment]
cordova: 4.3.1
Noje.js: v0.12.5

**Comment by don** [comment]
Can you try creating a test project with the newest version of Cordova? It's possible the older Cordova 4.3 needs Node 0.10.x.

**Comment by georgedemian** [comment]
i install it again, and it works thank you!
