### ISSUE TITLE
PhoneGap Build version is outdated

### ISSUE THREAD

**Issue by subb** [don/BluetoothSerial#151]
I'm using PhoneGap Build to build the iOS version of my app since I don't have access to a Mac. However, the current version in the PhoneGap plugin repository is 0.3.3, which is a bit behind the latest 0.4.3 version that contains many useful fixes.

Is it possible to update the PhoneGap Build version?

Thanks

**Comment by don** [comment]
You can install the plugin from plugins.cordova.io now http://docs.build.phonegap.com/en_US/configuring_plugins.md.html.

**Comment by mnadler** [comment]
plugins.cordova.io is being deprecated, is it possible to migrate to NPM?

**Comment by don** [comment]
Yes, the next release will be on NPM, hopefully next week.

I've created #160 to track this.
