### ISSUE TITLE
No free context space; the APP has registered 20 services.

### ISSUE THREAD

**Issue by adamos42** [don/BluetoothSerial#153]
Hello here, I have an other problem with the connecting:
```
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] No free context space; the APP has registered 20 services.
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] connectNative: The FD (0) doesn't exist.
E/BluetoothSerialService( 7706): java.io.IOException: [JSR82] connect: Connection is not created (failed or aborted).
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] No free context space; the APP has registered 20 services.
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] connectNative: The FD (0) doesn't exist.
E/BluetoothSerialService( 7706): Couldn't establish a Bluetooth connection.
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] abortNative: The FD (0) doesn't exist.
E/BluetoothSerialService( 7706): unable to close() Insecure socket during connection failure
E/BluetoothSerialService( 7706): java.io.IOException: [JSR82] close: abort() failed.
E/BluetoothSerialService( 7706): 	at android.bluetooth.BluetoothSocket.close(BluetoothSocket.java:443)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService$ConnectThread.run(BluetoothSerialService.java:388)
E/BluetoothSocketService.cpp(  490): [JSR82][JNI] abortNative: The FD (0) doesn't exist.
E/BluetoothSerialService( 7706): close() of connect Insecure socket failed
E/BluetoothSerialService( 7706): java.io.IOException: [JSR82] close: abort() failed.
E/BluetoothSerialService( 7706): 	at android.bluetooth.BluetoothSocket.close(BluetoothSocket.java:443)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService$ConnectThread.cancel(BluetoothSerialService.java:408)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService.start(BluetoothSerialService.java:94)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService.connectionFailed(BluetoothSerialService.java:232)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService.access$500(BluetoothSerialService.java:27)
E/BluetoothSerialService( 7706): 	at com.megster.cordova.BluetoothSerialService$ConnectThread.run(BluetoothSerialService.java:392)
```
I installed the plugin with the ```cordova plugin add com.megster.cordova.bluetoothserial``` 
Android version is ```4.2.2``` and Cordova version is ```5.1.1```

**Comment by don** [comment]
I haven't see this. Do you have more than 20 bluetooth devices paired?

Sometimes the Bluetooth stack has problems and rebooting the device helps.

**Comment by adamos42** [comment]
Im tryed rebooting, but the problem was not solve and I not have 20 bluetooth devices paired, just 2. The problem is in the abort() method, someway they cant close the socket.

**Comment by don** [comment]
@adamos42 what phone are you using? Is the problem specific to one device? Is the problem only on 4.2.2? Can you create the simplest app that duplicates the problem? I can see if I can duplicate on my hardware.

**Comment by adamos42** [comment]
@don Evolveo Strongphone Q4 with Android 4.2.2, No the problem appears not only one device but one device type, im using also a Caterpillar B15Q with Android 4.4.2 where the problem is not exists. Sot the problem is with the Android version + Cordova version, because soon as I build with 5.1.1 Cordova the problem appears.

The simpliest app: try connect to something on Android 4.2.2 and build the app with Cordova 5.1.x

On the Android 4.2.2 with Cordova 4.x im still get the errors in https://github.com/don/BluetoothSerial/issues/111 but I can handle it, so its just annoying thing.

**Comment by don** [comment]
@adamos42 I can't duplicate this on a Google Galaxy Nexus running 4.2.2. with Cordova 5.1.1

Unfortunately, I think this is a hardware or Android issue with that particular phone model.
