### ISSUE TITLE
Stop searching devices

### ISSUE THREAD

**Issue by AvsThiago** [don/BluetoothSerial#156]
Hey guys, is there some way to i stop the devices search or the plugin stops by itself?

**Comment by don** [comment]
[bluetoothSerial.list](https://github.com/don/BluetoothSerial#list) stops scanning after 3 seconds on iOS.

https://github.com/don/BluetoothSerial/blob/a6bdd6c632ac8d856de2636f3f660659606a6dcd/src/ios/MEGBluetoothSerial.m#L136

**Comment by sclearion** [comment]
Can this be adjusted. The native Bluetooth discover on my ipod doesn't even take that little. Its takes like 5-7 seconds at least! 3 seconds is waaay to short.

**Comment by don** [comment]
Modify the ObjectiveC to adjust the timeout https://github.com/don/BluetoothSerial/blob/a6bdd6c632ac8d856de2636f3f660659606a6dcd/src/ios/MEGBluetoothSerial.m#L136

Be sure to adjust the scan and the timer.

**Comment by sclearion** [comment]
I did and it worked thank you. Still gotta figure out this list() issue
