### ISSUE TITLE
Android To Android Connectivity

### ISSUE THREAD

**Issue by chhrahul** [don/BluetoothSerial#163]
Hi @don 

Have you updated the plugin files so that it connects and transfer messages between 2 android devices ?

Hope to hear from you soon.

Thanks
Rahul

**Comment by ateufel** [comment]
this is being discussed in issue #50 already, does not seem like there is a real solution already though...

**Comment by don** [comment]
@chhrahul This is a duplicate of #50.

This would be a nice feature, but something that is not currently supported. You could try the fork mentioned in https://github.com/don/BluetoothSerial/issues/50#issuecomment-66405396. This is not something I need right now, so I'm not likely to add it any time soon.
