### ISSUE TITLE
Failure statuses

### ISSUE THREAD

**Issue by equidna** [don/BluetoothSerial#167]
Every time I use BluetoothSerial functions they show only the fail status independently of the function I use.
What could I be doing wrong?

The js code is:

document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    $(function(){
        $( "#enable" ).click(function() {
            bluetoothSerial.enable(
                function() {
                    alert("Bluetooth is enabled");
                },
                function() {
                    alert("The user did *not* enable Bluetooth");
                }
            );
        });
        $( "#isEnabled" ).click(function() {
            bluetoothSerial.isEnabled(
                function() {
                    alert("Bluetooth is enabled");
                },
                function() {
                    alert("Bluetooth is *not* enabled");
                }
            );
        });
        $( "#discover" ).click(function() {
            bluetoothSerial.discoverUnpaired(function(devices) {
                alert("as");
                devices.forEach(function(device) {
                    console.log(device.id);
                })
            }, failure);
            function failure() {
                alert("abc");
            }
        });
    })
}

I added the following line to config.xml:

\<gap:plugin name="com.megster.cordova.bluetoothserial" version="0.3.3"/\>

I'm using an Android smartphone, and I'm building the app online with "phonegap build".

**Comment by don** [comment]
Your code worked OK for me. Make sure you're using an up to date version of PhoneGap.

    npm install -g phonegap

I use phonegap to install the plugin, rather than editing config.xml. Note that the plugin id changed for newer versions of the plugin.

    phonegap plugin add cordova-plugin-bluetooth-serial --save    

I run compile and deploy to my phone with the command line.

    phonegap run android --device

You need to run this on a phone. Bluetooth won't work in the emulator.

**Comment by equidna** [comment]
Does that means that when I install a plugin with:

phonegap plugin add ...

In the CLI I don't need to edit the config.xml?

**Comment by don** [comment]
If you're using the CLI on your machine, you do *not* need to edit config.xml. Simply install the plugin with phonegap.

    phonegap plugin add cordova-plugin-bluetooth-serial

If you're using [PhoneGap Build](http://build.phonegap.com) you need to add the following to config.xml.

    <gap:plugin name="cordova-plugin-bluetooth-serial" source="npm" />

With PhoneGap build you'd build with 

    phonegap remote build android

**Comment by equidna** [comment]
Looks like its not a problem with this particular plugin but with any plugin. I'm still new at phonegap.
I'm probably doing something wrong, the code works fine, except for the plugins.
Would you be so kind to direct me to some kind of tutorial or help about plugins? I know this no longer has anything to do with the issue, but I would appreciate the help.

**Comment by equidna** [comment]
Found the problem. I thought phonegap and phonegap build where the same system. But the installation of plugins are made in diferent ways:

phonegap:
phonegap plugin add cordova-plugin-bluetooth-serial --save

phonegap build:
add the line "<gap:plugin name="cordova-plugin-bluetooth-serial" source="npm" />" into config.xml
