### ISSUE TITLE
Phonegap build 

### ISSUE THREAD

**Issue by equidna** [don/BluetoothSerial#168]
When installing BluetoothSerial via phonegap build I tested the plugin using 3 API methods:
- bluetoothSerial.enable
- bluetoothSerial.isEnabled
- bluetoothSerial.discoverUnpaired

bluetoothSerial.isEnabled works fine while "enable" and "discoverUnpaired" give me an error:

TypeError: Object #<Object> has no method 'enable'
TypeError: Object #<Object> has no method 'discoverUnpaired'

Does BluetoothSerial has a newer version with those methods, that no longer support phonegap build?

**Comment by don** [comment]
Older version of the plugin will have fewer methods.

You should be using version 0.6.4 of the plugin from NPM. The old version of the plugin in the PhoneGap Build repository is no longer supported. 

PhoneGap Build supports installing plugins from NPM, so there's no reason not to use the latest version of the plugin.

Add this line to config.xml

    <gap:plugin name="cordova-plugin-bluetooth-serial" source="npm" />

**Comment by equidna** [comment]
When you said version 0.6.4 did you meant 0.4.4?

**Comment by don** [comment]
Yes

**Comment by equidna** [comment]
Thank you.
