### ISSUE TITLE
The plugin does not work in PhoneGap Developer App

### ISSUE THREAD

**Issue by TATIYA** [don/BluetoothSerial#172]
Hello,

I'm not able to connect my phone to my PC using the official dev app(http://app.phonegap.com/), is the plugin compatible with the official dev app?

**Comment by don** [comment]
This plugin is *not* part of http://app.PhoneGap.com. if you want to do Bluetooth Low Energy, https://github.com/don/cordova-plugin-ble-central *is included* with the PhoneGap developer app.

**Comment by don** [comment]
You could suggest to the Adobe team that they should include this plugin in PhoneGap Developer App.
