### ISSUE TITLE
iOS - error with serialBluetooth.connect() 

### ISSUE THREAD

**Issue by PetruMagdeleine** [don/BluetoothSerial#173]
Hello,

First of all thank you so much Don, for providing the add-on.
I work with the https://github.com/improvisio-software/BluetoothSerial fork of the plugin.
I try to open a connection to exchange data between mobile devices and a computer ( Macbook pro with classic bluetooth), with the RFCOMM protocol.

It's work well with Android devices, but got a error with iOS (Ipad iOS 9.0) when I try the 
serialBluetooth.connect()  method :

Xcode debug :
Device could not use correct protocol!
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** setObjectForKey: object cannot be nil (key: name)

Thanks,
Petru.

**Comment by don** [comment]
If you're using the ExternalAccessory, you should really file bugs against that fork.

I'd guess your accessory name is nil.  https://github.com/improvisio-software/BluetoothSerial/blob/master/src/ios/BluetoothSerial.m#L40

See if you can name your accessory or add some code around that line to handle nil.
