### ISSUE TITLE
Does this plugin work on windows 8.1

### ISSUE THREAD

**Issue by doughri** [don/BluetoothSerial#176]
I tried this plugin on android it works fine with. I would like to know if it works on Windows 8.1 PC?
Thanks!

**Comment by don** [comment]
@doughri right now it's just Windows Phone 8 support (Silverlight). I expect the Windows APIs are similar, so the code could be ported to Cordova for Windows (meaning Windows 8.1, Windows Phone 8.1 and Windows 10.) If the C# code compiles on Windows 8.1 is might work if you copy files to the right places. More likely, things will need to be rewritten (probably in JavaScript.)
