### ISSUE TITLE
run on windows or linux?

### ISSUE THREAD

**Issue by sledgeh** [don/BluetoothSerial#180]
Since this is node.js app. Is there any hack to make `BluetoothSerial` work with Ubuntu linux or Windows?

**Comment by don** [comment]
There are versions of Cordova that can run on Windows and Linux, but the code would need to be modified to support the platforms.

There's good Node.js packages that will run on Windows, Linux and OS X.
For Bluetooth Classic try [node-serialport](https://github.com/voodootikigod/node-serialport).
For Bluetooth Low Energy I use [noble](https://github.com/sandeepmistry/noble).
