### ISSUE TITLE
isConnected issues

### ISSUE THREAD

**Issue by swfredrik** [don/BluetoothSerial#183]
I would like to check isConnected before Im about to send any data, but it always keep returning false... (even thow Im connected)

 bluetoothSerial.isConnected(disconnect, connect(deviceAddress));

When I'm connected I have no problem sending and receiving data. 

Have you experienced anything like it?

**Comment by don** [comment]
Are you seeing this on iOS or Android?

**Comment by swfredrik** [comment]
android
