### ISSUE TITLE
Unconnecting Bluetooth

### ISSUE THREAD

**Issue by equidna** [don/BluetoothSerial#188]
Is there a BluetoothSerial method to turn off the Bluetooth connection?
Thank you.

**Comment by don** [comment]
The plugin does not contain a function to disable the Bluetooth adapter. 

Android's BluetoothAdapter has a [disable method](http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#disable()) but it's not intended to be called without user input. For enable, Android provides an intent to prompt the user and handle enabling the adapter. Unfortunately there's no intent to disable the adapter, which makes implementing disable more complex.

Currently, the best solution would be to open the Bluetooth preferences using [bluetoothSerial.showBluetoothSettings()](https://github.com/don/BluetoothSerial#showbluetoothsettings) and let the user disable the adapter.
