### ISSUE TITLE
Getting proximity

### ISSUE THREAD

**Issue by ospfranco** [don/BluetoothSerial#190]
Is there any way to get the discovered bluetooth peripherals proximity data?

**Comment by don** [comment]
If you're using iOS, you can use [bluetoothSerial.readRSSI](https://github.com/don/BluetoothSerial#readrssi).

**Comment by roeku** [comment]
Why iOS? Can't we use it on android?

**Comment by don** [comment]
@roeku the implementations are different. iOS uses Bluetooth Low Energy and there are APIs to for getting the RSSI of connected devices. 

Android used Bluetooth Classic. I haven't see APIs for RSSI.
