### ISSUE TITLE
Android to android bluetooth communication

### ISSUE THREAD

**Issue by RobinDesir** [don/BluetoothSerial#192]
Hey Don, 

Is it possible to communicate with another Android device ? I keep getting the "Unable to connect to device" error ... 

Thx in advance for your answer, 
Robin.

**Comment by RobinDesir** [comment]
I read that it was because Android to Android communication via this plugin wasn't supported in another issue, is it still true ?

**Comment by don** [comment]
@RobinDesir Android to Android isn't supported by default. If you see Issue #50 some people have android-to-android working in forks of the plugin.

Ideally once someone has this working and tested, they'll submit a pull request so it can be part of the library.

Closing this as a duplicate of #50

**Comment by RobinDesir** [comment]
Thx for your quick answer don.
