### ISSUE TITLE
bluetoothSerial skips all functions

### ISSUE THREAD

**Issue by Frakcool** [don/BluetoothSerial#195]
I've tried the following code:

    var scanPorts = function() {
        if (deviceMode == 'serial') {
            chrome.serial.getDevices(onGetDevices);
        } else if (deviceMode == 'bluetooth') {
            bluetoothSerial.setDiscoverable(0);
            bluetoothSerial.readRSSI(
                function(rssi) {
                    console.log(rssi);
                },
                function(error) {
                    console.log('Error1');
                }
            );
            bluetoothSerial.list(
                function(devices) {
                    devices.forEach(function(device) {
                        console.log(device.id);
                    })
                },
                function(error) {
                    console.log('Error2');
                }
            );
        }
    }

But I get no output on the console, it enters the bluetooth section, and allows bluetooth to be visible for unlimited time, however on the next lines I don't get anything, I've added a breakpoint in every if but it never enters success / failure functions.

I'm using Cordova 5.4.1, over Mac OS El Capitan with this [device](http://support.verifone.com/fstore/0a463145bbfccb42_46679154_14cff38c75a_-6767/DOC087_023_EN_B_VX_600_Bluetooth_Installation_Guide.pdf) (Verifone VX600), it's a Point Of Sale (POS) Device. I call the above function every 3 seconds, we're also using nwjs and from there we're trying to get this information. Do you have an idea what's going on?

**Comment by don** [comment]
I'd try pairing the VX600 with an Android device, then using bluetoothSerial.list to find the device and bluetoothSerial.connect to connect to it.

The VX600 needs to support SPP for this to work.

Since it's a Bluetooth Classic device, it will only work Android with this plugin.
