### ISSUE TITLE
NSString *uuid =  p.identifier.UUIDString; `

### ISSUE THREAD

**Issue by halygo** [don/BluetoothSerial#198]
Hello @sandeepmistry

` I have a littel problem : NSString *uuid = p.identifier.UUIDString; `

"Use of undeclared identifier 'p'"

can you help 

Thanks

**Comment by don** [comment]
@halygo I think you're using old code. This issue should have been fixed with #154.

Make sure you're using the new plugin id cordova-plugin-bluetooth-serial. If you use the old id, com.megster.bluetoothserial, you'll get an older version of the plugin that doesn't work with the latest Xcode.

**Comment by halygo** [comment]
Ok ;)
