### ISSUE TITLE
Device's own Bluetooth Address

### ISSUE THREAD

**Issue by rheligon** [don/BluetoothSerial#208]
Hi, I like all of the functionalities of the plugin but I need to get the device's own bluetooth Address at some point for my project (ionic/cordova).
Is there a way to get that done with this plugin? how can i do it?

**Comment by don** [comment]
This library does not have the function you want.

On Android you can get the device address from the Bluetooth Adapter http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getAddress()

I'm not sure if you can get the Bluetooth address on iOS.
