### ISSUE TITLE
The correct way to connect multi device

### ISSUE THREAD

**Issue by hypery11** [don/BluetoothSerial#216]
I've read the previous same[ issue](https://github.com/don/BluetoothSerial/issues/58), there are many solutions but can not work actually,
is there any right way to connect multi device?

**Comment by don** [comment]
@hypery11 right now there's not a good way to connect to multiple devices. 

/cc @AndrewListerHK

**Comment by Shikoruma** [comment]
My fork should work on Android thanks to @hypery11
plugin https://github.com/Shikoruma/BluetoothSerial
test app on ionic https://github.com/Shikoruma/blueserialtest

**Comment by AndrewListerHK** [comment]
That's great news Shikoruma.  I'll try it out and let you know.

**Comment by andrewinHK** [comment]
What do you think about making the mac address the first argument in all the functions?  It would kind of make it a little more standard as Don's original code used bluetoothSerial.connect(macAddress_or_uuid, connectSuccess, connectFailure);

**Comment by Shikoruma** [comment]
I thought of it but I wanted this version backward compatible with the current version.
I also think that most user will not use the multi-connection.

**Comment by andrewinHK** [comment]
Ah yes - of course.

**Comment by lovelyelfpop** [comment]
Try this one https://github.com/bugnano/cordova-plugin-networking-bluetooth
