### ISSUE TITLE
SimpleSerial/Android - Null BLE List

### ISSUE THREAD

**Issue by lauleehong** [don/BluetoothSerial#224]
I've built the Android version of SimpleSerial using a Moto G on Android Studio, following the instructions closely. When I ran the code, I'm returned with a null string for the list of nearby BLE devices, but I clearly have a peripheral switched on right beside (cross-checked with other BLE scanning apps). I have also tried the android version for Chat, and I'm not getting any BLE devices listed. 

When I hard-coded my peripheral's MAC Addr in the js/index.js macAddress, I'm was unable to get a connection as well. Any insights on this matter?

I've built similar on iOS and is working perfectly fine.

**Comment by don** [comment]
The Android version of this plugin only supports Bluetooth Classic. For BLE support on Android try [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central). See the [bluefruitle example](https://github.com/don/cordova-plugin-ble-central/tree/master/examples/bluefruitle) for code that uses a UART-like BLE service.
