### ISSUE TITLE
discoverUnpaired always return [] object in Android 6

### ISSUE THREAD

**Issue by mumairali** [don/BluetoothSerial#226]
Hi Don,

I am trying to retrieve unpaired devices list but each time it returns empty object each time. I have tried following after studying docs:

```
          bluetoothSerial.discoverUnpaired(
                function(result) {
                    app.display(JSON.stringify(result));
                },
                function(error) {
                    app.display("Problem while discovering");
                }
            );
```

NOTE: Phone search shows all unpaired devices list but I am wired why above code is not working.

_I have tested it on Lollipop it is working perfect_

Is this plugin not updated with android 6 or I am doing something wrong?

screenshot attached: 
![20160505_150018](https://cloud.githubusercontent.com/assets/6498132/15041033/74ed1c00-12d2-11e6-8add-634a410a55e8.png)
![screenshot_20160505-150111](https://cloud.githubusercontent.com/assets/6498132/15041038/7842c74c-12d2-11e6-9aa4-54cdd91757d1.png)

**Comment by don** [comment]
This might be an Android permission problem.  Until I fix it, can you edit config.xml and target Android 22

    <preference name="android-targetSdkVersion" value="22"/>

**Comment by Sundypha** [comment]
I tried this evening to get a quick fix. It's very dirty! maybe on the weekend I will create a fork and make it pretty for a PR.
Try to replace your BluetoothSerial.java with this gist: https://gist.github.com/Sundypha/9259044aeb2d4e17929989adba4a1b79

It works on my device but I don't know if I break older sdkVersions.

**Comment by Sundypha** [comment]
see #194

**Comment by mumairali** [comment]
thanks @Sundypha for quick help..

I am getting error on line number:224, 252 in android studio
```
cordova.requestPermissions <- can't resolve
cordova.hasPermission <- can't resolve
```

That mean I should wait for fix. I hope that will be available very soon :-)

thank you @don

**Comment by Sundypha** [comment]
@mumairali try to update the platform `cordova platform update android` maybe this updates the cordova files. I use this in my ionic app with ng-cordova.js.  Currently I'm traveling. I could help you tomorrow.  I totally forgot about the manifest.xml you can add it in the plugin.xml but you already figured that out.

**Comment by L2Gui** [comment]
Same issue here :-/
