### ISSUE TITLE
Error in bluetoothSerial.list

### ISSUE THREAD

**Issue by zindello** [don/BluetoothSerial#231]
Hi Don,

First of all I'll say Thanks in Advance. Without people like you we wouldn't be able to do some pretty cool stuff :)

So I've followed your chat example, and I'm trying to get the List to callback to a modified version of the onDeviceList function you've provided in the chat example, except I'm using a select drop-down and using the javascript to populate the device list in that drop down.

However it appears it's not working, I understand it will get no results if running on a PC, however in safari I'm seeing the following error:

TypeError: success_cb is not a function. (In 'success_cb(devices)', 'success_cb' is undefined)

Is this because I'm testing the code on a PC and not the device it's self? Have you got any good suggestions for retrieving the error messages from the actual device?

My onDeviceList is posted below though I suspect it's not actually getting to the point where it's firing my function. Device is an iPhone 6S.

	onDeviceList: function(devices) {
		
		var select = document.getElementById("lstBLE");
		var length = select.options.length;
		for (i = 0; i < length; i++) {
			select.options[i] = null;
		}
		
		devices.forEach(function(device) {
			var opt = document.createElement('option');
			opt.value = device.id;
			opt.innerHTML = device.name;
			select.appendChild(opt);
			select.options.disabled = false;
		});
		
		if (devices.length === 0) {
			var opt = document.createElement('option');
			opt.value = "";
			opt.innerHTML = "No Devices Found";
			select.appendChild(opt);
			select.options.diabled = true;
		}
	},

Thanks again.

**Comment by don** [comment]
When you run in the browser there's a different javascript file https://github.com/don/BluetoothSerial/blob/3c5134339efbcea7449a498aa3b2660f779360dd/src/browser/bluetoothSerial.js

Based on the error, you're passing a non-function (or nothing) to a function that expects a callback.
