### ISSUE TITLE
Print HTML

### ISSUE THREAD

**Issue by safanmomin** [don/BluetoothSerial#242]
How can I print out HTML?
I'm using the code like this;
bluetoothSerial.write("`<h1>testing</h1>`", function(){alert('success')}, function(){alert('error')});
instead of printing out the 'testing' it prints out '`<h1>testing</h1>`' as it is.

**Comment by don** [comment]
[bluetoothSerial.write](https://github.com/don/BluetoothSerial#write) sends data to the remote device. I guess you're connected to a printer? If you're seeing `<h1>testing</h1>` my plugin did it's job. If your printer supports HTML, you might need to put it in a different mode. More likely you need to send some printer specific code (PostScript, PCL, etc) to get formatted text.
