### ISSUE TITLE
Raw data not working correctly

### ISSUE THREAD

**Issue by acondurache** [don/BluetoothSerial#243]
I am using a Force Sensor and trying to access the data. In the Arduino Serial Monitor I get the following data:

```
Resistance: 3301060.00 ohms
Force: 0.47 g

Resistance: 3301060.00 ohms
Force: 0.47 g

```
...

But when I access the data via  **bluetoothSerial.subscribeRawData()** using code below:
```
 bluetoothSerial.subscribeRawData(function (data) {
            var bytes = new Uint8Array(data);
            console.log(bytes);
        }, $scope.failConnect);
```

Output from above:
```

[101, 115, 105, 115, 116, 97, 110, 99, 101, 58]
appctr.js:23 [32, 53, 54, 55, 54, 46, 52, 52, 32]
appctr.js:23 [111, 104, 109, 115, 13, 10, 70, 111, 114, 99]
appctr.js:23 [101, 58, 32, 50, 55, 52, 46, 48, 52, 32]
appctr.js:23 [103, 13, 10, 13, 10]
appctr.js:23 [82]

```
I get a bunch of random arrays that doesn't correspond to the data I get above from the Arduino Serial Monitor

Any ideas why I am not getting the correct data?

**Comment by don** [comment]
@acondurache did you solve this? what was the problem?

**Comment by Purushothama-VS** [comment]
Hi Don,
I am also facing similar issue and getting similar data like above, how to resolve this.
