### ISSUE TITLE
It has not been updated for a long time

### ISSUE THREAD

**Issue by noobsoft** [don/BluetoothSerial#247]
It has not been updated for a long time, when to support Android 6 & Android 7

**Comment by don** [comment]
The plugin will work on Android 6 if you target android-22. There's also a pull request with Android 6 permissions. You could use that fork. 

I haven't looked at Android 7 yet, but the same strategy should work for now. 

The plugin will be updated, but I don't have a schedule. I update the plugins when I personally need a feature, my clients need a feature, or I have free time. I share a lot of code so other people can take advantage of it, but there no guarantees about updates.

**Comment by noobsoft** [comment]
@don OK,Than you!
