### ISSUE TITLE
how to print with mix small and big font size to thermal bluetooth printer

### ISSUE THREAD

**Issue by noeprivacy** [don/BluetoothSerial#250]
Hi Don,

i use phonegap to create my app, i already create app and it's work correctly to print from my android to the printer.. so, when i want to print some text for small size i don't know how to do. can you help me?
i use bluetoothSerial.write command for write to printer. please give some example.. thank you very much

**Comment by don** [comment]
@noeprivacy This plugin just handles the Bluetooth necessary to get the data from your phone to your printer. You'll probably need some printer specific commands to get the text to change size.
