### ISSUE TITLE
Can I connect to bluetooth low energy device from android?

### ISSUE THREAD

**Issue by vdzundza** [don/BluetoothSerial#251]
Hi there,

I figured out that android 4.3 supports BLE . Can I use rhis module for connection to IoT device which supports only connection via BLE.

**Comment by vdzundza** [comment]
@don Hoe can I use cordova plugin with react-native?

**Comment by don** [comment]
@vdzundza I've never used React Native. You might be able to use this https://github.com/axemclion/react-native-cordova-plugin

If it works, please let me know.
