### ISSUE TITLE
ios asks to turn on bluetooth every time the app is started if bluetooth is off 

### ISSUE THREAD

**Issue by FutoRicky** [don/BluetoothSerial#252]
Everytime the app is started it asks to turn on bluetooth (which is annoying) is the bluetooth is off on the device. Is there any way to avoid this?

**Comment by don** [comment]
@FutoRicky For now, if you want to stop this, you'll need to modify the plugin and pass CBCentralManagerOptionShowPowerAlertKey when creating the manager.

https://developer.apple.com/reference/corebluetooth/cbcentralmanageroptionshowpoweralertkey?language=objc

https://github.com/don/cordova-plugin-ble-central/issues/174#issuecomment-179775652
