### ISSUE TITLE
Get connected device info.

### ISSUE THREAD

**Issue by rjurado01** [don/BluetoothSerial#253]
It is possible to get the connected device info (address, id or name) ?
I don't see any method to get this info.

Thanks.

**Comment by LingboTang** [comment]
@rjurado01 You can do it with `bluetoothSerial.list` to list all settings for all devices, or you can also use `bluetoothSerial.showBluetoothSettings`

**Comment by rjurado01** [comment]
@LingboTang `bluetoothSerial.list` doesn't return which device is connected and `bluetoothSerial.showBluetoothSettings` doesn't work for me because I need connected device info from code to show: "Device connected: XV9040" in my application.

**Comment by don** [comment]
There's no direct way to get the connected device info. You can use @LingboTang's suggestion of using bluetoothSerial.list. Save the MAC address (or UUID) that you pass to bluetoothSerial.connect and filter the results from bluetoothSerial.list to get the name.
