### ISSUE TITLE
No address can be specified when I use function "isConnected"

### ISSUE THREAD

**Issue by LingboTang** [don/BluetoothSerial#256]
I think it's good feature to add. When people want to detect if their phone is connected to some certain devices, they might have the need to know which one exactly. For ex, some people want to memorize a device, and when they start their app again, they want to know if that device is automatically connected or not.

**Comment by don** [comment]
@LingboTang this plugin only connects to one device at a time so [bluetoothSerial.isConnected](https://github.com/don/BluetoothSerial#isconnected) doesn't need any arguments. If you want to connect to multiple BLE devices you can try https://github.com/don/cordova-plugin-ble-central
