### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by aravindt11** [don/BluetoothSerial#257]
Hi Don,
Thanks for the awesome work.

Does the code support windows 10 devices.I am trying to debug in my windows 10 laptop.I get "command not found".

Thanks
Aravind

**Comment by don** [comment]
You probably need this pull request https://github.com/don/BluetoothSerial/pull/212 for Windows 10. I need to test and merge this into master.

**Comment by aravindt11** [comment]
I tried to work on the pull request..It has few bugs working on it..I will try to request new merge request soon.
