### ISSUE TITLE
It is possible to scan for ble devices on background?

### ISSUE THREAD

**Issue by orgixmh** [don/BluetoothSerial#258]
Hello there, im using your code for my home door lock and working like a harm, but
im wondering if it possible to scan for ble devices while application is in background and create a notification when ble device found? Also can this pass apples app store?
Thanks Don for sharing, i cant be done it without your code.

**Comment by don** [comment]
I haven't done background scanning with this plugin. For [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central) background scanning works on iOS if you [add extra configuration to run in the background](https://github.com/don/cordova-plugin-ble-central#background-notifications-on-ios). That same modification should work for this plugin. I have a sample project for background scanning and notifications https://github.com/don/ble-background. 

You should be fine submitting an app to the app store with this plugin.
