### ISSUE TITLE
How I can send a number in hex?

### ISSUE THREAD

**Issue by josb86** [don/BluetoothSerial#266]
Hi, I am trying to send a number with the next code:

var direccion = 3;

bluetoothSerial.write(direccion, 
              function success(){}, 
              function error(failure){alert(failure)});

but I get the error "bad base-64", Is not it possible to send a number in this plugin?

**Comment by don** [comment]
You need to send the data as a String "3" or as bytes.  I recommend sending the data in a Uint8Array or ArrayBuffer.

    var data = new Uint8Array([3]);
    bluetoothSerial.write(data, success, failure);

See https://github.com/don/BluetoothSerial#write
