### ISSUE TITLE
discoverUnpaired in combination with setDeviceDiscoveredListener

### ISSUE THREAD

**Issue by mspace** [don/BluetoothSerial#269]
Using Android 5.1.1 @samsung device.

``` javascript
        bluetoothSerial.setDeviceDiscoveredListener(function (device) {
          console.log('Found device on the fly: ' + device.id);
          addDeviceToList(device);
        });

        bluetoothSerial.discoverUnpaired(function (unpairedDevices) {

          bluetoothSerial.clearDeviceDiscoveredListener();
          console.log("Finished searching for unpaired devices");

          for (var i = 0; i < unpairedDevices.length; i++) {

            var device = unpairedDevices[i];

            var d = ({
              "name": device.name,
              "address": device.address,
              "id": device.address,
              "class": device.class
            });

            addDeviceToList(d); // add to array if not already in (checking by MAC address)
          }
        }, failure);
```

If I change the order of upper functions: 1.  bluetoothSerial.discoverUnpaired() and then 2. bluetoothSerial.setDeviceDiscoveredListener, function setDeviceDiscoveredListener doesn't work. Only bluetoothSerial.discoverUnpaired() is triggered. Documentation states this:

**setDeviceDiscoveredListener**

> Register a notify callback function to be called during bluetooth device discovery. For callback to work, discovery process must be started with discoverUnpaired. There can be only one registered callback.

Probably solution is trivial, but I'm not really sure what is meant by 

> For callback to work, discovery process must be started with discoverUnpaired.

**Comment by don** [comment]
You need to call `bluetoothSerial.setDeviceDiscoveredListener` before `bluetoothSerial.discoverUnpaired` for this to work.

When discoverUnpaired starts, it calls the device discovered listener if it has been set. When you reverse the order, you set it too late.
