### ISSUE TITLE
Send commands to device and get responses

### ISSUE THREAD

**Issue by filipimosquini** [don/BluetoothSerial#270]
Hello devs,

I have a device serial that i use for receive data, but now, i need to send specific commands for this device and get responses. For send this commands, i use the  _write_ method but the success callback from this method is just an "OK". 

The sent command for device is 02 0D 0A (using the Uint8Array)  and the correct return from this command would be a following sequence: 02 30 37 35 35 30 37 33 31 30 30 30 31 35 30 0D 0A

I already use method _subscribeRawData_ for get the received responses  to the device (in an interval from five seconds after the device is connected to smartphone).

I would like to know how i do to send commands to device serial and receive a sequence from bytes above together with the data already sent from device serial.

**Comment by don** [comment]
@filipimosquini send and receive are separate. If you registered a callback with `bluetoothSerial.subscribeRawData`, you should receive responses from your hardware.
