### ISSUE TITLE
How stop  discoverUnpaired

### ISSUE THREAD

**Issue by estvmachine** [don/BluetoothSerial#274]
Hi, im really want to know how i can stop the scan of discoverUnpaired, i see exists setListeners, maybe an hack?.

**Comment by don** [comment]
Discover unpaired wraps Android's [BluetoothAdapter.startDiscovery](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#startDiscovery()). The discovery will automatically stop after about 12 seconds.
