### ISSUE TITLE
More detailed error messages on connection fail

### ISSUE THREAD

**Issue by soptrau** [don/BluetoothSerial#280]
Hi,
would it be possible to expand the error messages received on a connection fail?
"Unable to connect to device" isn't that much of a help solving the problem :/

What are the problems  that could lead to such a connection fail?

**Comment by don** [comment]
Unfortunately there's no a lot of info from the iOS or Android on why it couldn't connect.

**Comment by soptrau** [comment]
That's too bad, but nothing you could really change then.
Thank you for taking your time anyways.
