### ISSUE TITLE
Programmatically enter paring pin

### ISSUE THREAD

**Issue by mumairofficial** [don/BluetoothSerial#281]
Hi @don,
Actually it is not a bug. Is this possible in BluetoothSerial plugin to pair with Bluetooth device by entering PIN pro-grammatically. This feature will be very helpful. 

Following will link will give idea to implement this feature,
http://stackoverflow.com/questions/19047995/programmatically-pair-bluetooth-device-without-the-user-entering-pin

I have read this #55 Did you worked on this? (Curious) 

Thank you in advance :)

**Comment by don** [comment]
@mumairofficial I have not implemented setPin

**Comment by don** [comment]
@mumairofficial see https://github.com/don/BluetoothSerial/pull/114 for some code that does what you're looking for. I haven't merged that pull request since it uses private apis.
