### ISSUE TITLE
Methods are not being executed on using given  programming syntax

### ISSUE THREAD

**Issue by amritss47** [don/BluetoothSerial#282]
Hi @don ,

Sorry my title might be wrong, as I am not from programming background. I am trying to build a ionic app for sending commands to arduino.  Problem is that it is given a function can be executed in following way : 
```

BluetoothSerial.isEnabled(
    function() {
        console.log("Bluetooth is enabled");
    },
    function() {
        console.log("Bluetooth is *not* enabled");
    }
);
```
However, this syntax does not seem to be working at all. Instead Im having to use "BluetoothSerial.isEnabled().then" which is kind of difficult way for me... ... I would like to use given syntax wherein whernever I call a method, I would insert one success and failure function in it..

What I am doing wrong ? Thanks

**Comment by don** [comment]
This plugin injects a global variable named bluetoothSerial. (lowercase B).  

Ionic2 provides an Angular wrapper around this plugin named BluetoothSerial https://ionicframework.com/docs/v2/native/bluetooth-serial. 

My code uses takes 2 arguments, a success callback and a failure callback. The Ionic Wrapper code returns a promise, forcing you to use the then() syntax.

You don't have to use the Iconic wrappers. You can call the plugin directly by changing BluetoothSerial to bluetoothSerial. Cordova should automatically add bluetoothSerial to the global namespace when the plugin is installed. Note that Ionic (and Angular) make things a bit more complex, so bluetoothSerial might not always be in scope in your code.  You probably need to declare bluetoothSerial in your code to keep the TypeScript compiler happy.

    declare var bluetoothSerial: any;
