### ISSUE TITLE
Connect successfully but failed to write data

### ISSUE THREAD

**Issue by sy1016** [don/BluetoothSerial#283]
Hi Don,

Can this plugin work with PIC micro controller (HC-06)?
I try with "Chat" sample and it's connected successfully, it able to receive/read data from the Bluetooth device, however, it failed when send/write data to the Bluetooth device

Kindly advice.
Thanks.

**Comment by sy1016** [comment]
Hi Don, i send command "AT" and it should response with "Ok" but then it failed even with line feed added.

bluetoothSerial.write("AT\n", success, failure);

it will response with any input i key in, if i key in "AT", it will response with "AT", if i enter "Hello" and send, the response came back as "Hello", which is incorrect

**Comment by don** [comment]
@sy1016 some devices will accept AT commands, but it needs to be in mode that can accept them. Sometimes you need to send +++.  (You'll need to be using Android for this to work.)

Some devices might not like the strings, you could try encoding the data yourself into a byte array. See [bluetoothSerial.write](https://github.com/don/BluetoothSerial#write) for more info.
