### ISSUE TITLE
Ionic 2 with angular 2

### ISSUE THREAD

**Issue by oularrea** [don/BluetoothSerial#287]
Hello I would like to know when the Observer onComplete function of the subscribeRawData method is called or subscribe, I need to know this to know when it finishes sending the information of the Bluetooth device and to be able to process the information asynchronously

Thank you very much. Greetings, I hope you can help me.

**Comment by don** [comment]
@oularrea You'd need to check the source of the [Ionic wrapper](https://ionicframework.com/docs/v2/native/bluetooth-serial/). (That's not code that I wrote or maintain.)

For iOS subscribe is a BLE notification and called when data is received. For Android it's processing the stream of incoming Bluetooth data.
