### ISSUE TITLE
Clarification in documentation

### ISSUE THREAD

**Issue by scarabdesign** [don/BluetoothSerial#290]
Looks like the documentation for "disconnect" was copy pasta from the "connect" outline, as it says "Success callback function that is invoked when the connection is successful". 

I'm moving on with the assumption that you mean "when the disconnection is successful", but what does an unsuccessful disconnect look like? Does it run the error callback or does it send a Boolean with the success callback?

**Comment by don** [comment]
Currently you'll always get a success callback from both [iOS](https://github.com/don/BluetoothSerial/blob/c5e59a46354af6dc8f65c84b261cc7d77bdfdf8b/src/ios/MEGBluetoothSerial.m#L75) and [Android](https://github.com/don/BluetoothSerial/blob/408a03a005565c6910f721170c21e0dd22c98c14/src/android/com/megster/cordova/BluetoothSerial.java#L126). If the failure is implemented in the future it will call the error callback.
