### ISSUE TITLE
Bluetooth connection automatically disconnects after 20+ seconds

### ISSUE THREAD

**Issue by bot101** [don/BluetoothSerial#299]
I implemented BluetoothSerial in an Ionic app I am working on. The app connects successfully with a HC-06 bluetooth module for arduino but automatically disconnects after about 20 seconds. I am implementing this in an Ionic 2 app and an Android 6.0 device.

**Comment by don** [comment]
You might need to occasionally send data to keep the connection alive. Alternately there might be a timeout setting on the HC-06.
