### ISSUE TITLE
Can we have a option to detect bluetooth device type(Cod)?

### ISSUE THREAD

**Issue by samever7** [don/BluetoothSerial#300]
Hi don,

Do we have some functions or something by which we can get the type of bluetooth devices?

We get the list and in that a filed for list items named 'class', like below:
`{
        "class": 276,
        "id": "10:BF:48:CB:00:00",
        "address": "10:BF:48:CB:00:00",
        "name": "Nexus 7"
    }`

 [Here](https://www.bluetooth.com/specifications/assigned-numbers/baseband) has a definition of CoD, which by class we can know what type of the device is, such as computer, phone, lan or peripheral. 

So maybe we can add a function for this one? Or it should be dev's option to do this?

**Comment by don** [comment]
I'd recommend filtering the discovered devices in your JavaScript code.
