### ISSUE TITLE
no method to get the UUID

### ISSUE THREAD

**Issue by mitsol** [don/BluetoothSerial#304]
I did not find any solution to get the UUID of a discovered device.

I thought it would be part of the device i get with the following code:

` onDiscoverDevice: function(device) {
        console.log(JSON.stringify(device));
 }`

Unfortunately it only holds name, id (MAC), advertising and rssi

EDIT: Sorry put it in the wrong project! Should be part of cordova-plugin-ble-central.

**Comment by don** [comment]
On Android devices have MAC addresses. iOS hides the MAC address behind a UUID.
