### ISSUE TITLE
Sending HEX values

### ISSUE THREAD

**Issue by drekbr** [don/BluetoothSerial#305]
Dear Don,

I did read a lot of information over the net and can't do write hex values using bluetoothserial. I need to write the command AFFD00DF, 16 bit mode. I have tested uint8 and uint16, but didn't work. Can you help me?

Thanks.

**Comment by don** [comment]
[bluetoothSerial.write](https://github.com/don/BluetoothSerial#write) takes a bunch of different formats. Typically I'll create a Uint8Array when sending binary data.

    var data = new Uint8Array(4);
    data[0] = 0xAF;
    data[1] = 0xFD;
    data[2] = 0x00;
    data[3] = 0xDF;
    bluetoothSerial.write(data, success, failure);
