### ISSUE TITLE
Name device property not always returned when calling discoverUnpaired method several times

### ISSUE THREAD

**Issue by yannbarrault** [don/BluetoothSerial#306]
Using version @0.4.4, when using discoverUnpaired method call, sometimes the result doesn't contains a name property but only the device address ? 

`window.bluetoothSerial.discoverUnpaired(function(success){

  // success contains a table with each entry is a device object

  // the first time I always have an object with an address and a name

  // I don't have the name but only the address...

  // Does the plugin give back the result before resolving the name ?

}`

**Comment by don** [comment]
discoverUnpaired runs a Bluetooth Classic discovery and send the data to JavaScript. If you're not seeing the name, Android doesn't have it. There's not much the plugin can do.

Does this happen on every phone or just some phones?
Does this happen with most peripherals or just specific peripherals?
If you run the scan a second time can you see the names?

It's possible you need to increase the Android scan time or decrease the advertising interval on the Bluetooth device to consistently get the names.
