### ISSUE TITLE
Why connectInsecure is not supported on iOS?

### ISSUE THREAD

**Issue by Ladeia** [don/BluetoothSerial#307]
I want to make a insecure connection with my IOS and my arduino BLE.

But I dont know this is not supported, someone can help-me?

**Comment by don** [comment]
bluetoothSerial.connectInsecure is Bluetooth Classic only and added to work around an Android bug.

When you're using this plugin with iOS it uses Bluetooth Low Energy to connect, which doesn't have the connectInsecure functions. BLE will connect to your device without a passphrase.

**Comment by Ladeia** [comment]
thanks, this solution resolv my problem
