### ISSUE TITLE
Microchip BLE Not Supported

### ISSUE THREAD

**Issue by PulsarLabs** [don/BluetoothSerial#312]
I am using Microchip's BM77 SPP Duel Mode Module to connect to iOS.  I know all I need to do to make this compatible is to substitute the rx and tx uuid parameters in the BLEDefines.h, but I am using phonegap build and I am not sure how to go about using my updated version of this plugin.  Any suggestions?

**Comment by don** [comment]
PhoneGap build should be able to install a fork of this plugin from your GitHub repo. If you get it working, send a pull request. If want to talk about adding BM77 support to the plugin send me an email.
