### ISSUE TITLE
Communication with another BLE device

### ISSUE THREAD

**Issue by sanavilpa** [don/BluetoothSerial#313]
Hello all,

I am developing an application to communicate 2 BLE devices, one of them is a mobile phone.
I need to send an arrays of bytes (APDUs) and receive the response from the other BLE device.  I am using a combination of Bluetooth Central and Bluetood Serial plugins, but when I write the command I only receive an "OK". 

Are there some way of have a response from the other device when a command is send?

`this.ble.connect(this.deviceID).subscribe(peripheralData => {
    console.log(peripheralData.characteristics);
    this.characteristics = peripheralData.characteristics;
    this.connecting = false;

     var data = new Uint8Array(5);
    data[0] = -78;
    data[1] = 2;
    data[2] = 20;
    this.bluetoothSerial.write(data.buffer).then((deviceData)=> {
        // not sure of returning value, probably a boolean
        console.log(deviceData);

        }, error => {
            console.log(error);
        }
    );

    this.navCtrl.pop();
  
    },
    peripheralData => {
      console.log('disconnected');
      });
 }`

**Comment by don** [comment]
For Bluetooth Low Energy I suggest using [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central). Using cordova-plugin-ble-central you can connect to another device that is running a BLE service.

You can connect to an existing BLE service or implement your own with native code or  [cordova-plugin-ble-peripheral](https://github.com/don/cordova-plugin-ble-peripheral). Currently cordova-plugin-ble-peripheral only works with iOS.
