### ISSUE TITLE
receive file

### ISSUE THREAD

**Issue by hamdysdiri** [don/BluetoothSerial#316]
Hello,
I would to use the BluetoothSerial plugin to establish a connection with an Arduino.
I would to receive a file from the the arduino to my smartphone.
Is the BluetoothSerial will help me to acheive this goal or i should find another solution.
Thank you at advance.

**Comment by don** [comment]
File transfer works best over Bluetooth Cllassic. If you have a Bluetooth Classic radio for your Arduino and an Android phone this will work. If you have an iPhone, you'll need to have a Bluetooth Low Energy radio on your Arduino. You can transfer files with Bluetooth Low Energy but it's painfully slow.
