### ISSUE TITLE
bluetoothSerial.Read how to return barcodes separately

### ISSUE THREAD

**Issue by iakwvina** [don/BluetoothSerial#317]
Hi,
When I am scanning multiple codes, the bluetoothSerial.Read returns all of them in one line. Their length isn't the same. Is there any code to  take each code length to separate them later?

**Comment by don** [comment]
If the data is delimited with something like a line feed you could use [bluetoothSerial.readUntil](https://github.com/don/BluetoothSerial#readuntil).

**Comment by iakwvina** [comment]
I noticed that the data had a empty character, which was not visible inspecting the data element, but only using data.length(). So I did something like this, to separate them:  
```
var correctData = data.split("");
var correctData_arr = correctData.join("").trim().split(/\s/); 
```

**Comment by don** [comment]
Thanks for the update.
