### ISSUE TITLE
Send JSON data from one device to another for Auth request

### ISSUE THREAD

**Issue by princeJio** [don/BluetoothSerial#319]
Hi @don  i used your plugin and successfully managed to connect using bluetoothSerial.connect() .Now i want to send some JSON data for auth request 

Sample JSON
  var data = {
           "Type": "AuthRequest",
           "Category": "MobileApp",
           "UID": "7ba04b7a-6037-450c-810a-813df47b0da5",
           "Password": "pass"
         };

and then to send some subrequest data after success callback to start getting the Json data from that device,So which BluetoothSerial method i have to use to implement this using this plugin

Thanks in advance

**Comment by don** [comment]
Use [bluetoothSerial.write](https://github.com/don/BluetoothSerial#write) to send data.
