### ISSUE TITLE
working web version

### ISSUE THREAD

**Issue by GPlay97** [don/BluetoothSerial#320]
The android version is working very well. But what is with the browser? It seems that the browser target is just a simulation and does not really connect to a device or handle any data.
Is a web implementation for browser planned? So I can interact with bluetooth directly via the browser? If not - is there any alternative? Maybe a fork of this plugin?

Thanks in advance

**Comment by don** [comment]
> browser target is just a simulation and does not really connect to a device or handle any data.
correct

Web Bluetooth works on Chrome macOS, Linux, ChromeOS, and Android. See https://googlechrome.github.io/samples/web-bluetooth/
