### ISSUE TITLE
Unable to Read the Message from another device  

### ISSUE THREAD

**Issue by princeJio** [don/BluetoothSerial#322]
Hi @don I use bluetoothSerial.write to write a sting "Helllo World " to another successfully connected mobile but in success response it shows just ok , no complete response got in success and on another device to which i send data , i receive data using both   bluetoothSerial.read and bluetoothSerial.suscribe
but for both i got no response message .how to resolve this issue. Thanks in advance
**Sender phone code**
bluetoothSerial.write(data, success,error)

**Receiver phone code**
bluetoothSerial.subscribe("<br>", msgreceived, bt_error);

**Comment by don** [comment]
This plugin doesn't really support phone to phone communication. On Android it expects to connect to a Bluetooth Classic RFCOMM SPP service. On iOS it expects to connect to a Bluetooth Low Energy service that looks like SPP. It supports BLE services from RedBear, Adafruit, Laird, Nordic and BlueGiga.

For Bluetooth Classic, some people have forks that support RFCOMM between Android devices. If you're using Bluetooth Low Energy, some phones could initiate a connection with [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central) and other phones could provide a service with [cordova-plugin-ble-peripheral](https://github.com/don/cordova-plugin-ble-peripheral).
