### ISSUE TITLE
Running a scheduled task when app is in background

### ISSUE THREAD

**Issue by peteb5893** [don/BluetoothSerial#323]
I'm working on a Cordova Android app, and was wondering if it possible to communicate to a bluetooth device and trigger a response while the app is in the background. For example, when a user switches to another app or puts their phone on standby, the app would continue to send commands at timed intervals to a bluetooth device and interpret the response. Depending on the response, the app would either do nothing, or trigger an alert/sound or notification to the user to take action. Has anyone been able to achieve something like this?

My end goal is to be able to send a command to a bluetooth enabled meter at set time intervals e.g hourly or daily etc , even when the app is in the background, and trigger a notification to top-up the meter credit if the meter balance falls beneath a lower limit. 

Any help would be greatly appreciated.

Many thanks,
Peter

**Comment by don** [comment]
On Android Bluetooth *should* work in the background. I haven't written any apps with Bluetooth Classic in the background.
