### ISSUE TITLE
Empty unpaired devices list on iOS10

### ISSUE THREAD

**Issue by lmark83** [don/BluetoothSerial#324]
Hi,

I'm using the plugin in order to connect my application to a Bluetooth Thermal Printer; it work fine on Android but on iOS 10 when I call the list function I always get 0 devices.

Am I missing any configuration or iOS 10 is not supported by the plugin?

Thank you in advance.
Mark

**Comment by don** [comment]
iOS only supports some Bluetooth Low Energy devices with SPP like services. Currently RedBearLab BLE hardware, Adafruit Bluefruit LE, Laird BL600, and BlueGiga are supported. If your printer has as a BLE service, see https://github.com/don/BluetoothSerial#supporting-other-ble-hardware

**Comment by lmark83** [comment]
Thank you Don! 

Could you please suggest me any vendor that produces thermal printers equiped with the BLE modules you listed? Unfortunately at the moment I am not abke to edit the defines but I still want to keep your plugin in my app.

Thank you again
Mark

**Comment by don** [comment]
Sorry, I haven't done much with thermal printers.
