### ISSUE TITLE
Ionic 3 =>couldn't pair with lenovo vibe k5 because of an incoorect pin or passkey.

### ISSUE THREAD

**Issue by AsreshSharma** [don/BluetoothSerial#326]
bellow code
 selectDevice(address)
  {         
      let alert = this.alertCtrl.create({
      title: 'Connect',
      message: 'Do you want to connect with?',
      buttons: 
      [
            {
              text: 'Cancel',
              role: 'cancel',
              handler: () => {
              console.log('Cancel clicked');
            }
      },
            {
              text: 'Connect',
              handler: () => 
              {
                //this.bluetoothSerial.connectInsecure(address).subscribe(this.success, this.fail);  
                    console.log("Connected Conn " + address);
                    this.bluetoothSerial.connect(address).subscribe((data:Observable<string>) => {

                      console.log("Connect " + JSON.stringify(data));

                      this.bluetoothSerial.available().then(data =>{

                        console.log("Available " + JSON.stringify(data));

                        this.bluetoothSerial.read().then(data =>{

                          console.log("Read " + JSON.stringify(data));
                          this.navCtrl.push(WelcomePage,data);

                        });
                      });
                    }, fail => {
                      console.log("Connected Error : " + JSON.stringify(fail));
                    });
              }
            }
      ]
    });
    alert.present();

  }

**Comment by don** [comment]
When I'm using Bluetooth Classic on Android I try and pair the device with the phone before running my app.

See #114 for some code that lets you programmatically enter a PIN. I haven't merged that pull request since it uses private apis.
