### ISSUE TITLE
Arduino serial communication

### ISSUE THREAD

**Issue by unseen1980** [don/BluetoothSerial#329]
Hi all,

I connected successfully my ionic app to an arduino attached bluetooth module(HC-05) but when I try to write to something to serial the characters are garbage.

![1](https://user-images.githubusercontent.com/2386570/29477867-2d467b50-8462-11e7-84a2-0b4f7bc1666f.PNG)
![2](https://user-images.githubusercontent.com/2386570/29477872-2fe44d92-8462-11e7-88d4-a14d957edcc6.PNG)

I tried different speeds etc but no luck. Any ideas? @don

**Comment by don** [comment]
On my Arduino hardware I usually read Bluetooth data from SoftwareSerial and write to Serial. Some radios need [a series of setup commands](https://github.com/don/BluetoothSerial/blob/master/examples/Chat/Arduino/Chat_SeeedShield/Chat_SeeedShield.ino#L57-L69) which I usually copy and paste from an example or the documentation. Unfortunately I haven't used the HC-06. Some my other sample Arduino code might give you some ideas to try https://github.com/don/BluetoothSerial/tree/master/examples/Chat/Arduino

**Comment by unseen1980** [comment]
Thanks, don, I'll give it a try and get back to you!
