### ISSUE TITLE
bluetooth headset and socket 

### ISSUE THREAD

**Issue by navinSing** [don/BluetoothSerial#331]
Looking to connect bluetooth for headdset and socket with andoid:  
https://developer.android.com/reference/android/bluetooth/BluetoothHeadset.html
https://developer.android.com/reference/android/bluetooth/BluetoothServerSocket.html

Any help/code guidelines/examples will be extremely helpful.

**Comment by don** [comment]
@navinSing I think the best thing would be create a BluetoothHeadset Cordova plugin. You should be able to use the Android code from this plugin as a guide.
