### ISSUE TITLE
Background permissions popup on iOS 10

### ISSUE THREAD

**Issue by lmark83** [don/BluetoothSerial#332]
Hi,

On iOS the popup that asks the user to grant the permissions is showed in background; thus the app needs to be iconized in order to accept.

Is there a way to either fix this issue or show this popup at runtime at the first access to the plugin?

Thnak you for your support.
Mark

**Comment by don** [comment]
You mean the permission dialog is hidden by the app? I've never seen that. Do you have a simple project that duplicates the issue?
