### ISSUE TITLE
Ble device Bluetooth connection problem   

### ISSUE THREAD

**Issue by sahalt** [don/BluetoothSerial#338]
This version does not work for me.
 Can you please help me ?I have tried   this Bluetooth serial plugin with (cordova).But i can't able to connect the two android device.Please suggest ,what I need to change in code.
i tried number of examples but all example are giving the connection problem 
Example: connection error ,unable to connect device  

I downloaded the project
copied the Chat example in a separate place
cordova plugin add com.megster.cordova.bluetoothserial
cordova platform add android
cordova build - > and run
but again I see the same issue. when I try to connect android to android instantly says disconnected. 
connection failed   

https://github.com/tomvanenckevort/BluetoothSerial ?

**Comment by don** [comment]
This code does not support communication between 2 Android devices. You linked to Tom van Enckevort's fork of this plugin that adds the capability.

Linking two Android devices is possible as Tom's version demonstrates. This is not a feature I need so it's not in my plugin.
