### ISSUE TITLE
I cant print any language other than english

### ISSUE THREAD

**Issue by rakesanug** [don/BluetoothSerial#340]
Hi,

I developed sencha Touch Application. in that application i print some content using bluetooth serial plugin. i can print english language. but i cant print any other language like tamil,hindi.

            var printStr = ["\n                     தமிழ்\n\n"];
               printStr.push("\n     தமிழ்");
               printStr.push("\n     తమిళ")
               printStr.push("\n    तामिल");
              bluetoothSerial.connect(localStorage.bluetoothMacAddress, function(success){
                console.log(success);
                for(var p = 0; p < printStr.length; p++){
                    var print = printStr[p];
                    console.log(print);
                    bluetoothSerial.write(print, function(suc){
                    }, function(fail){
                        alert("Bluetooth printer not able to print");
                        return;
                    });

                }

            }, function(failure){
                alert("Bluetooth printer not connected");
                console.log(failure);
            });

i get output like this:

![p_20171107_121731](https://user-images.githubusercontent.com/19207023/32480668-f2a1abd0-c3b5-11e7-9289-e8584949f939.jpg)

**Comment by don** [comment]
@rakesanug write doesn't handle UTF-8 or UTF-16, you'll need to encode the data yourself. See https://github.com/don/BluetoothSerial/issues/240#issuecomment-227931365 for one way to do this.
