### ISSUE TITLE
ios ble long delay

### ISSUE THREAD

**Issue by gengshenghong** [don/BluetoothSerial#344]
Hi @don ,

Thank you for this great library, I've used it for my Android (classic bluetooth) and now I am testing the ble on ios. According to what I heard, the package is only 20 bytes and the package interval is about 20ms (It seems we cannot change this on ios??). Does it mean the max speed of ble is:
1s / 20ms * 20 bytes = 1000 bytes/s
Which is quite a low speed for real-time communication with arduino sometimes.
Above is the theoretical result, hope you can confirm my understanding.

Also, I did test with real code in cordova, I generate random bytes and send to a bluetooth module  (I've make it work after change the UUIDs) in a whole, the bluetooth module will echo back, at the cordova side, I'll store the received bytes (subscribeRawData) and compare with the sent ones, when it is same, the test is done and I'll calculate the duration from sent to received. My results as below (the baud rate is 9600):
1. when I send more than 108 bytes, data will lost. is it normal?
2. when I send 108 bytes, the duration is about 500ms! which is quite a long delay. Any idea?
3. is the "write" in this library "write with response" or "write without response"? I heard "write without response" is about twice faster than "write with response".

I used the same test code for spp (classical bluetooth), and I can get about full 80% baud rate (depends on the module though). Appreciate your suggestions to make the response faster for ble + ios. Any comments are welcome.

Thanks,
Shenghong

by the way, key code for my testing (logic should be correct as I used it for spp test too).
``` javascript
speedTest: function() {
        btRecvData = new Uint8Array();
        
        var strData = randomWord(false, 109);
        var uint8array = new TextEncoder("utf-8").encode(strData);
        console.log(uint8array);
        console.log(strData);
        console.log(uint8array.length);

        var startTime = 0;
        var endTime = 0;

        gRecvCheckHandler = (data) => {
            //console.log(data);
            var temp = arrayCompare(data, uint8array);
            if (temp) { // data are same, we have received all we sent!
                endTime = new Date().getTime();

                gRecvCheckHandler = null;
                btRecvData = new Uint8Array(); // clear the data for next test
                app.display("Test done");
                app.display(endTime - startTime);
            }
        };

        startTime = new Date().getTime();
        bluetoothSerial.write(strData, function() {
            app.display("Write ok!");
        }, function() {
            app.display("Write fail!");
        });
    },
```

the code to subscrible:
```javascript
bluetoothSerial.subscribeRawData(function(data) {
            var bytes = new Uint8Array(data);
                // merge the data
                btRecvData = mergeTypedArraysUnsafe(btRecvData, new Uint8Array(data));
                if (gRecvCheckHandler) {
                    gRecvCheckHandler(btRecvData);
                }
                //console.log(btRecvData);
            }, function() {
                app.display("subscribe failed!");
            });
```

**Comment by don** [comment]
@gengshenghong iOS uses BLE. BLE is very slow. Many peripherals are limited to 20 bytes in a characteristic. iOS will support BLOB reads and writes that can transparently write up to 500 bytes in a characteristic with Bluetooth 4.x. The max characteristic size very dependent on the hardware. Bluetooth 5 increased the max characteristic size to 2000 bytes.

Data can get dropped if you send too fast with writeWithoutResponse or notify. If you need more control over BLE try https://github.com/don/cordova-plugin-ble-central
