### ISSUE TITLE
Android does not scan for new devices.

### ISSUE THREAD

**Issue by romanlutai** [don/BluetoothSerial#351]
Hello,
I am using this combination:
```
    bluetoothSerial.setDeviceDiscoveredListener(function (device) {
      console.log(device.id);
      btListHTML.insertAdjacentHTML('beforeend',`<li onclick="bt.pair('${device.name}','${device.id}')">${device.name}</li>`);
    }, function(failure){console.log(failure);} );
    bluetoothSerial.discoverUnpaired( function(devices){
      bluetoothSerial.clearDeviceDiscoveredListener();
    }, function(failure){console.log(failure);} );
```
To scan bluetooth devices on Android phone.

Though, seems like either `setDeviceDiscoveredListener()`, or `discoverUnpaired()` are not doing anything. They are not returning failure or information about the device, and they do not see bluetooth devices, even though, the phone itself can see unpaired devices.

Moreover, other functions from the library seems like working fine: before the code written above, the app is succesfully using `bluetoothSerial.isEnabled()`, `bluetoothSerial.enable()`, and `bluetoothSerial.list()`.

What could be the issue?
Br, Roman

**Comment by andersborgabiro** [comment]
Do you request BLUETOOTH_ADMIN permission?

**Comment by don** [comment]
Closing old issue, assuming permissions fixed the issue.

**Comment by Zoidster** [comment]
I am running into the same problem and adding the BLUETOOTH_ADMIN permission didn't fix it.
Just as OP said, isEnabled and list are working fine but `discoverUnpaired` and `setDeviceDiscoveredListener` don't emit any data.
