### ISSUE TITLE
Check if connection still valid

### ISSUE THREAD

**Issue by fiyi** [don/BluetoothSerial#353]
I am using the bluetooth plugin with ionic 3 and angular and am testing the app on an Android device. 
My app is set up to write to and read from a bluetooth device. Before a write function is called, I use the isConnected() function to check the status of the connection before writing. The problem is this function returns a valid connection even if there is none (I turn off the BT device to check this) The write function when called also writes to the bt device (without a connection) and calls the success handler of the write method.
In the ionic native bluetooth serial plugin it takes about 4-5 seconds for the bluetooth connection status to be updated by the observable from the connect() method. And if a write method is called in this period I get this unreliable behaviour.

Am I missing something else here? How can I make sure that the write function is writing only if there is a valid connection? 

Here is my code - 

    writeData(data) {
	this.bluetoothSerial.isConnected().then(() => {
		this.bluetoothSerial.write(data).then((success) => {
			console.log('written: ' + data + ' success ' + success);
			alert(data + " Written to device!");
		},
		(error) => {
			alert('error writing: ' + error);
		});
	}, (error) => {
		console.log('Operation not completed as device not connected');
		alert('Device is not connected');
	});
    }

**Comment by don** [comment]
Don't check the connection state. Once you connect, you'll get a success callback. Later on, if the device disconnects,

**Comment by LRonHubs** [comment]
He's saying if you start your app with your device already connected, there's no way to tell whether it's actually connected or simply in the list of previously paired devices.  This is a huge problem for me as well.

Android will auto-pair to a device that's turned on and nearby, if it has previously been paired to the device. The library lacks functionality in recognizing this type of connection and disconnection.

**Comment by don** [comment]
@LRonHubs if the connection is made with the plugin the state should be correct. I haven't used auto connect with Bluetooth classic. If the plugin is able to communicate, it should be able to determine the connected state. If this isn't working for you, it sounds like a bug. isConnected is probably the best place to do this.

If the plugin can update values when it's auto connected, we'll just need to update [mState](https://github.com/don/BluetoothSerial/blob/86017ed84ec8fcf0e98c27f11ff698f6f9e0e8c7/src/android/com/megster/cordova/BluetoothSerialService.java#L84). I'd really help me if you could run your app with Android Studio and the Java debugger and try and figure out when the autoconnect happens in the code so I know where to update mState.

**Comment by fiyi** [comment]
@don Thank you, yes thats what I went with - relying on the Observable.
