### ISSUE TITLE
Write Barcode On Serial Device

### ISSUE THREAD

**Issue by amongdawiner** [don/BluetoothSerial#361]
Hi I managed to write to serial thermal printer to print a receipt, but I don't know how to write a barcode or QR code on it.

**Comment by don** [comment]
@amongdawiner this plugin give you serial communication. Printing a barcode or QR code is probably printer specific. I'm guessing you'll need to send some PCL or control codes to get the printer to do what you want. A lot of people ask about this so please update the issue with more details if you find a solution.
