### ISSUE TITLE
Print QRCode

### ISSUE THREAD

**Issue by soesantos** [don/BluetoothSerial#362]
Hello don,
pls advice how to print QRCode using this great plugin!!

thanks
GBU

**Comment by don** [comment]
@soesantos this plugin give you serial communication. Printing QR code is probably printer specific. I'm guessing you'll need to send some PCL or control codes to get the printer to do what you want. A lot of people ask about this so please update the issue with more details if you find a solution.

**Comment by soesantos** [comment]
hi don,
i try to print QR code generated to ionic card div (red mark) this is Base64 String of Image  ,

i send code "write" to printer 
"
let PrintData = document.getElementById("SKU")
bluetoothSerial.write(PrintData, success, failure);
"
but the output on the printer is print the string of base64 image not print qr code picture
eg. 
![whatsapp image 2018-05-03 at 2 26 46 am 1](https://user-images.githubusercontent.com/38737763/39545046-23b42e42-4e7a-11e8-896c-8da4a4ceb8d8.jpeg)
![whatsapp image 2018-05-03 at 2 03 31 am](https://user-images.githubusercontent.com/38737763/39543962-d141d87e-4e76-11e8-902d-a8b0f2529f48.jpeg)
