### ISSUE TITLE
Issue with Connect returned observable in Ionic 3.

### ISSUE THREAD

**Issue by vivekmuthu1910** [don/BluetoothSerial#364]
This is the code I am running in android device using `ionic cordova run android --device` cli command.

```typescript
import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';
import { BluetoothSerial } from '@ionic-native/bluetooth-serial';

interface pairedDevice{
  name: string,
  address: string,
  id: string,
  class: number
}

@IonicPage()
@Component({
  selector: 'page-devices',
  template: `
<ion-content padding>
  <button ion-button block (click)="listPairedDevices()">List all Paired Devices</button>
  <button ion-button (click)="connect(device)" *ngFor="let device of pairedDevices">{{device.name}}</button><br />
  <button ion-button *ngIf="connectStatus" (click)="send('1')">On</button>
</ion-content>
`,
})

export class DevicesPage {
  public connectStatus = false;
  public pairedDevices: Array<pairedDevice>;

  constructor(private bluetoothSerial: BluetoothSerial) {
  }
  listPairedDevices(){
    this.bluetoothSerial.list().then((list)=>this.pairedDevices=list);
  }
  send(num: string){
    this.bluetoothSerial.write(num);
  }
  connect(device: pairedDevice){
    this.bluetoothSerial.connect(device.address).subscribe(
      ()=>{
        this.connectStatus=true;
      },
      ()=>{
        this.connectStatus=false;
      });
  }
}

```
When I list the paired devices, it is listing the devices. I tried to connect it with HC-05 module. When I click connect the device is connecting, but the subscribed function doesn't get called until some other event happens (like locking and unlocking the mobile, or clicking list paired devices etc.).

Can anyone please guide me through this.

Even `bluetoothSerial.write(num)` is also working. I tested it by removing the `*ngIf`. 
Only the subscribe functions `this.connectStatus=true;` and `this.connectStatus=false;` doesn't get executed until some other interaction happens.

**Comment by don** [comment]
Might be related to #353

**Comment by fiyi** [comment]
@vivekmuthu1910 I do not have this problem. I think its a model-view refresh issue. I am assuming that when you say this.connectStatus=true; is not executed what you mean is you do not see the button 'On' appear on the screen immediately. This could just be the way the mobile screen view is refreshed. 
Could you please insert an alert statement like - alert('Connected'); in your subscribe function and check if it is executed on connect?

**Comment by vivekmuthu1910** [comment]
Thank you @fiyi. The alert is working.
I was able to use ngZone to fix the UI update in async mode.
