### ISSUE TITLE
Correct way to recieve HEX data

### ISSUE THREAD

**Issue by PVoskr** [don/BluetoothSerial#368]
I send to my ionic app data that looks like this: 0xAA 0x81 0x5D 0x00 0xE8 0xBD 0x74 0x10 0x00 0x12
What I recieve on the phone looks like this: ��]�k���]
Most of symbols are already replaced with 0xFFFD symbol and I can't find a way to recieve correct data. 

I am using a weird code like this because it was the only way I could actually make my app recieve any data from the hardware:
```
this.bluetoothSerial.subscribeRawData().subscribe(
    (data) => {  
        this.bluetoothSerial.read().then(
          (data) => { 
            console.log('data = ' + data); // here we already have wrong symbols
            this.parseData(data) 
          });
      },
      (error) => {
        alert(error);
      });
```

**Comment by don** [comment]
When you subscribeRawData, observable receives the data. You should not call read() inside of subscribeRawData().

Try this

	this.bluetoothSerial.subscribeRawData().subscribe(
	    (data) => {
	  	// data is an ArrayBuffer, convert it to typed array
	    	var bytes = new Uint8Array(data);
		console.log(bytes);
	        this.parseData(bytes);
	    },
	    (error) => {
	    	alert(error);
	    }
	);

**Comment by PVoskr** [comment]
Thanks a lot. It worked
One last question. Is documentation up to date?

**Comment by don** [comment]
Yes the documentation is mostly up to date.
