### ISSUE TITLE
How to write HEX ?

### ISSUE THREAD

**Issue by zyzmoz** [don/BluetoothSerial#371]
Hello!
I've been trying to send '05' or '04' converted to HEX via .write command but my device don't perform the action wanted. I already tried to write string or HEX which were converted as an Array buffer without any success...

**Comment by don** [comment]
You need to pass bytes, not strings to [bluetoothSerial.write](https://github.com/don/BluetoothSerial#write)

    var data = new Uint8Array([0x04, 0x05]);
    bluetoothSerial.write(data, success, failure);

**Comment by zyzmoz** [comment]
Thank you so much... It was a huge mistake of mine...
