### ISSUE TITLE
Writing data in a row

### ISSUE THREAD

**Issue by viniciuspsw** [don/BluetoothSerial#373]
Hi. I'm trying to writing data in a row to an Arduino UNO with HC-06 module. This is my code:

`this.bluetooth.write('A');`
`this.bluetooth.write('B');`

But I'm receiving only the first command (A) in my Arduino. Should I add some delay between the functions or do something else? Thank you!

**Comment by don** [comment]
You can try adding a delay or waiting for the first callback to finish.
Can you combine the rows? bluetoothSerial.write("AB") or bluetoothSerial.write("A\nB")?
 Maybe it's the Arduino code? Can you write multiple lines to the Arduino using another Bluetooth app?
