### ISSUE TITLE
 Can you send an image to print?

### ISSUE THREAD

**Issue by miguelcs6** [don/BluetoothSerial#384]
Is there any option in this plugin to send to print an image?

Thank you

**Comment by miguelcs6** [comment]
good morning, I could communicate with the printer and send commands to print qr codes and barcode.

I will continue investigating, if I find the correct command and how to send the image I will share it.

Thank you

**Comment by Idigbe** [comment]
> good morning, I could communicate with the printer and send commands to print qr codes and barcode.
> 
> I will continue investigating, if I find the correct command and how to send the image I will share it.
> 
> Thank you

Hi @miguelcs6 , Please can you tell me how you are sending the QR and bar codes?. I am using cordova and cannot see any function call to achieve this

**Comment by bhiantara** [comment]
have any idea for print image? 
thanks..

**Comment by ademir10** [comment]
anybody did it? i'd like to print images and generate QRcode, thanks!

**Comment by don** [comment]
It depends on the printer. The plugin handles Bluetooth, you'll need to consult the printer documentation to see what type of data the printer is expecting to print an image.
