### ISSUE TITLE
how to use write function ,i need use esc/pos print order

### ISSUE THREAD

**Issue by baijygo** [don/BluetoothSerial#393]
![image](https://user-images.githubusercontent.com/22442221/50533919-1732ee80-0b6f-11e9-8143-8339916d90e7.png)

**Comment by baijygo** [comment]
I want to complete this

**Comment by uokivan** [comment]
@baijygo 
can you tel me how to do that, ok?
Thanks a lot & happy new year

**Comment by baijygo** [comment]
```
var hello = "01               膳呗外卖";
      hello += " \n ";
      hello += "王老七";
      hello += " \n ";
      hello += "出餐时间: 1月2日 15:28";
      hello += " \n ";
      hello += "-------------------------";
      hello += " \n ";
      hello +=
        "                                                                                                                                                                                 ";
      hello += "锅包肉";
      hello += " \n ";
      hello += "              *1   20.3";
      hello += " \n ";
      hello += "米饭";
      hello += " \n ";
      hello += "              *1   1.5";
      hello += " \n ";
      hello += "-------------------------";
      hello += " \n ";
      hello += "餐盒费               2";
      hello += " \n ";
      hello += "配送费               3";
      hello += " \n ";
      hello += "优惠券              -5";
      hello += " \n ";
      hello += "-------------------------";
      hello += " \n ";
      hello += "              顾客实付21.8元";
      hello += " \n ";
      hello += "15151996663";
      hello += " \n ";
      hello += "顾客";
      hello += " \n ";
      hello += "中国长安网微纳园";
      hello += " \n ";
      var data = this.stringToBytes(hello);
      console.log(data);
      var self = this;
      bluetoothSerial.connect(
        id,
        function() {
          console.log("Ble  connect success");
          bluetoothSerial.write(
            data,
```
![tim 20190102164332](https://user-images.githubusercontent.com/22442221/50585101-5a15fe80-0eae-11e9-9373-4218be2c937a.jpg)
the picture  is the code printe
the printer write  more less than i want to console
how can i config the printer write all i want to print

**Comment by uokivan** [comment]
can u share your code?
and I thank the error is:
-----------
  hello +=
        "   
-----------

**Comment by uokivan** [comment]
and what is the code of "stringToBytes" ?

**Comment by baijygo** [comment]
> ## 你能分享你的代码吗？
> 我感谢错误是：
> ## 你好+ = 
> “

function  stringToBytes  use to change utf-8 to gbk  and the `hello +=
"`  is  test code ,
i think that not problem because i can console all  i  want to print 
![image](https://user-images.githubusercontent.com/22442221/50619774-3bf3e100-0f36-11e9-8c00-bdb135cdf485.png)
![image](https://user-images.githubusercontent.com/22442221/50619883-10252b00-0f37-11e9-930d-337497a531c6.png)
the console is all  but  then i print is the part ,where i can config the printer print more or the data is part i do not know where have problem

**Comment by eki01** [comment]
@baijygo
how to fixed this problem?
