### ISSUE TITLE
Unable to Connect to Device (Android 4.4.2)

### ISSUE THREAD

**Issue by emwalters** [don/BluetoothSerial#40]
I am unable to connect to a Bluetooth based Barcode Scanner using the connect function.

I know the plugin is installed and working because it can find the device using the bluetoothSerial.list function.  I've also read over the given plugin examples and as far as I can tell my implementation is correct.  

I am passing the bluetoothSerial.connect function a hardcoded MAC address (this is just for testing and will change to a dynamic variable later).  Here is the JavaScript code i'm using:

bluetoothSerial.connect('00:06:66:A0:4F:36', function () {
    alert('connected');
}, function () {
   alert('There was a problem connecting to the bluetooth device.  Please reconnect        device.');
});

This code has never produced a successful connection.  Am i doing something wrong?  

Device info: Nexus 10 (Android vers. 4.4.2)

**Comment by Natgeo123** [comment]
my bluetooth asus padfone 2 having a problem. The on/off is okay. when on, there is icon bluetooth icon appear at the top of screen but always no nearby bluetooth device found. i need help. thank you
