### ISSUE TITLE
Add method readRaw

### ISSUE THREAD

**Issue by ruipalma** [don/BluetoothSerial#404]
Add method readRaw(), because the method read() returns a string and the javascript charCodeAt() do not return byte values over 127, so its impossible to work with binary data.

**Comment by jitendracodehacker** [comment]
Hi you can get it work done with following way 
this.BTSerialIface.subscribeRawData().subscribe( data => {
      //dont use read . 
  const bytes = new Uint8Array(data); //convert string to byte array
          console.log(bytes)
          });

**Comment by ruipalma** [comment]
Yes, thanks, that's what i'm doing, but it's not the same thing because in an application that you want:
Question -> Answer; Question ->Answer, with timeouts, error control, and flow management the subscribeRawData callback its called out of context and we need to use some workarounds to manage the flow.
I think that if the methods subscribeRawData and subscribeData exists, its coherent that the methods readRaw and read also exists.

**Comment by don** [comment]
subscribeRawData is the right way to do this with the plugin. In the past for more specific flow control, I've written new plugins for the specific devices.
