### ISSUE TITLE
How to check device is connected with bluetooth? and how to get connected device information?

### ISSUE THREAD

**Issue by sweety-wo** [don/BluetoothSerial#405]
How can I check my bluetooth device is connected or not with phone/tablet? and 
Is it possible to get connected device information and how can I get device connected device information?

**Comment by kingkarki** [comment]
Call list function to get list of the devices 

```
this.bluetoothSerial.list().then((s)=>{
    this.devices = s; // this will list all the avaliable devices. 
    console.log('bluetooth list avalible');
    console.log(s);

  }, (f)=>{alert(f)});
```

Call isConnected to check if the device is connected or not 

`  this.bluetoothSerial.isConnected().then((s)=>{alert('connected')}, (f)=>{alert(f)});
`
