### ISSUE TITLE
unsubscribe & unsubscribeRawData methods not availiable

### ISSUE THREAD

**Issue by JohnnyK84** [don/BluetoothSerial#408]
Not sure if anyone has encountered this issue or not. I have recently built an Ionic(v4) + Angular 8 application using this BluetoothSerial module. However, the unsubscribe() and unsubscribeRawData() methods are unavailable. Even checking out the index.d.ts file they are not listed here where all the other methods are listed.

Everything else works as expected however these methods are not available and this is in issue as I cannot manually kill the data stream from subscribe() and subscribeRawData() methods without restarting the App.

Any help or clarification on this issue would be much appreciated!

Cheers!

Edit...More info:
dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/bluetooth-serial": "^5.17.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.17.0",
    "@ionic/angular": "^4.7.1",
    "@ionic/storage": "^2.2.0",
    "cordova-android": "8.1.0",
    "cordova-plugin-bluetooth-serial": "^0.4.7",
    "cordova-sqlite-storage": "^3.4.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  }

**Comment by don** [comment]
The functions are available in this plugin, they're missing from the Ionic wrapper.

The best solution is to add them to the Ionic wrapper and send them a pull request. Alternately you can access the plugin directly from ionic and just call the functions.
