### ISSUE TITLE
Error when receiving two consecutive messages

### ISSUE THREAD

**Issue by brunyan** [don/BluetoothSerial#52]
When receiving two consecutive messages, in the handleMessage of BluetoothSerial the second message, msg.obj is refer to the first one! 

I resolve this by changing the run() in BluetoothSerialService, creating a byte[] in every cycle:

before:
<code>
        public void run() {
            Log.i(TAG, "BEGIN mConnectedThread");
            byte[] buffer = new byte[1024];
            int bytes;

            // Keep listening to the InputStream while connected
            while (true) {
                try {
                    // Read from the InputStream
                    bytes = mmInStream.read(buffer);

                    // Send the obtained bytes to the UI Activity
                    mHandler.obtainMessage(BluetoothSerial.MESSAGE_READ, bytes, -1, buffer).sendToTarget();

                } catch (IOException e) {
                    Log.e(TAG, "disconnected", e);
                    connectionLost();
                    // Start the service over to restart listening mode
                    BluetoothSerialService.this.start();
                    break;
                }
            }
        }
</code>

after:
<code>
		public void run() {
            Log.i(TAG, "BEGIN mConnectedThread");

            // Keep listening to the InputStream while connected
            while (true) {
                try {
                	byte[] buffer = new byte[1024];
                	
                    // Read from the InputStream
                    int bytes = mmInStream.read(buffer);

                    // Send the obtained bytes to the UI Activity
                    mHandler.obtainMessage(BluetoothSerial.MESSAGE_READ, bytes, -1, buffer).sendToTarget();

                } catch (IOException e) {
                    Log.e(TAG, "disconnected", e);
                    connectionLost();
                    // Start the service over to restart listening mode
                    BluetoothSerialService.this.start();
                    break;
                }
            }
</code>

**Comment by don** [comment]
can not duplicate with latest code
