### ISSUE TITLE
iPhone 5 BLE Connect to bluetooth 2.1?

### ISSUE THREAD

**Issue by Jie-Yang** [don/BluetoothSerial#76]
Hi Don,

Thank you for the plugin. I am just wondering whether it will work for the communication between BLE and Bt 2.1? or it has to be BLE on both side of the communication?

I am working on a app in which I need to build the BT connection between iPhone 5 (BLE) with a programming board with BT 2.1. It is working with Objective C.

Regards
Jie

**Comment by alexislg2** [comment]
What about if the device is MFI certified? See this SO post: http://stackoverflow.com/questions/25317939/can-you-program-bluetooth-2-1-on-ios
