### ISSUE TITLE
Unable to connect to device : Error Callback

### ISSUE THREAD

**Issue by gibbsvjy** [don/BluetoothSerial#78]
I have integrated plugin using CLI successfully and also listed connected android device but when i call bluetoothSerial.connect it is always go to error callback though Mac Address of remote device is correct.. I have also tried by put this into SETTIMEOUT but not working. please help me to resolve this issue I  am stucked in this problem.

**Comment by booybooy** [comment]
Hi Don,

I'm getting "Unable to connect to device" when attempting to connect to a paired device with its MAC address on Android. I have gotten the mac address via a call to bluetoothSerial.list(), so I'm certain that the address is correct. Here are some information regarding the devices:

Running on: Android 4.4.4
Bluetooth device: AB Shutter 3 (a camera remote)

Any suggestions on how to troubleshoot?

**Comment by don** [comment]
@ankittanna There is a fork that should work with Android to Android https://github.com/tomvanenckevort/BluetoothSerial

**Comment by don** [comment]
@booybooy I'd guess that the camera doesn't support Serial Port Profile (SPP). The plugin expects to connect to UUID 00001101-0000-1000-8000-00805F9B34FB.

You can modify the plugin if the camera is using a different UUID, but I'd expect is using another Bluetooth Profile.

**Comment by booybooy** [comment]
This is probably out of scope, but any idea how to find out which profile this camera remote supports, i.e via API? 

I'm also confused about: "The plugin expects to connect to UUID 00001101-0000-1000-8000-00805F9B34FB.". Does this pertain to only Android? Because BluetoothSerial.connect()'s documentation seems to suggest that if I were developing with iOS, I'd be able to pass in the UUID of the camera remote to make the connection.

**Comment by don** [comment]
No idea on your camera.

For Android, the plugin used Bluetooth Classic and uses Serial Port Profile (SPP). 00001101-0000-1000-8000-00805F9B34FB is a well known RFCOMM UUID.

For iOS, this plugin uses Bluetooth Low Energy (BLE). BLE doesn't have SPP, but a bunch of the devices have custom UART services that behave similar to SPP. On iOS you're passing in the iOS generated UUID that is a reference to the BLE device that was discovered when scanning for devices. BLE doesn't pair like Bluetooth Classic.

**Comment by Sasikumariosdeveloper** [comment]
Hai Don,
             AB Shutter3 have bluetooth address.using that address may i send alert to iphone devices.otherwise that bluetooth id might be helpful or not..seetings->general->about->bluetooth(this id)

**Comment by don** [comment]
@Sasikumariosdeveloper I don't think the AB Shutter 3 will work with this plugin. I expect the AB Shutter 3 just emulates a HID (keyboard) on iOS.

The Bluetooth id in the settings is the MAC address of the adapter. This plugin uses Bluetooth Low Energy on iOS. For BLE, iOS needs a UUID to connect. You get the UUID by scanning for Bluetooth devices.

**Comment by Sasikumariosdeveloper** [comment]
Good Morning Don,
                              How can i get UUID while scanning for bluetooth devices.

**Comment by equidna** [comment]
Hello, I'm trying to connect to a device that I'm sure it's UUID is:
"00001101-0000-1000-8000-00805F9B34FB"
Is there a fork of BluetoothSerial's plugin that covers this UUID?
Could this plugin work if I just changed:
UUID.fromString("7A9C3B55-78D0-44A7-A94E-A93E3FE118CE");
by:
UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
in BluetoothSerialService.java file, and try to establish a secure connection with my app?

**Comment by andymurakami** [comment]
Hi Don, 

I try to connect in a Blue Bamboo PM25-M bluetooth. But when I send de connect command. They returns same error : Unable to connect to device.

I use ionic + angularJS

 bluetoothSerial.connectInsecure(
                app.macAddress,  // device to connect to
                app.openPort,    // start listening if you succeed
                app.showError    // show the error if you fail
            );

The MAC Address is correct .

Do you have any solution ?

**Comment by uninxc** [comment]
@booybooy booybooy   follow code will be work!
` window.addEventListener('keydown', (e) => {
      console.log('keydown');
      console.log(e.key);
      console.log(e.keyCode);
    });

    document.addEventListener('volumedownbutton', (e) => {
      console.log('volumedownbutton');
      console.log(e);
      console.log(JSON.stringify(e));
    }, false);
    document.addEventListener('volumeupbutton', (e) => {
      console.log('volumeupbutton');
      console.log(e);
      console.log(JSON.stringify(e));
    }, false);`
