### ISSUE TITLE
Error sending data to Arduino

### ISSUE THREAD

**Issue by Vallekano** [don/BluetoothSerial#97]
Hi,

I am trying to use your plugin and almost everything is working fine. I can list the list of devices and connect to my arduino. The problem comes sending and receiving data.

If I send data from Arduino to my android device everything is fine but when I send data from Android to Arduino I get weird characters.

This is my Arduino code to test it:

```
void loop()
{
  if (btSerial.available()) {
    Serial.write(btSerial.read());
  }

  if (Serial.available()) {
    btSerial.write(Serial.read());
  }
}
```

With this code if I write "Hello" in the Arduino console, I get "Hello" in Android -> OK

But If I use this in my Android app:
```
bluetoothSerial.write("Hello",
            function (a, b) {
                console.log("Sent");
            },
            function (a, b) {
                console.log("Error sending");
        });
```

The data is sent but I am getting this in Arduino:
H,½ÿ
..and sometimes...
H,½

I have installed a serial app (BlueTerm) in my android mobile and if I send "Hello" with this app, I am getting "Hello" in Arduino so I think it's clear that the problem is in the plugin.

Any idea??

**Comment by don** [comment]
@Vallekano glad you got it working!
