### ISSUE TITLE
Property 'identifier' not found on object of type 'CBPeripheral*'

### ISSUE THREAD

**Issue by ttimmy** [don/BluetoothSerial#99]
Hi

Thanks for your plugin. Works great on Android.
On iOS, building the project shows this error on MEGBluetoothSerial.m line 491. I just added the plugin using Cordova 'plugin add'

**Comment by don** [comment]
@ttimmy I've seen this error once. Removing and re-adding the iOS project fixed it.

**Comment by don** [comment]
Assuming fixed.
